accent = "#5090f8"
cursor = "#ffeca0"
foreground = "#ffeca0"
background = "#210321"
selection_foreground = "#ffeca0"
selection_background = "#5090f8"

color0 = "#210321"
color1 = "#e71852"
color2 = "#7ad573"
color3 = "#f2c256"
color4 = "#5090f8"
color5 = "#9d58f0"
color6 = "#53d0bc"
color7 = "#ffafe4"
color8 = "#ab5488"
color9 = "#f8bdcd"
color10 = "#e4f7e3"
color11 = "#fcf3dd"
color12 = "#dce9fe"
color13 = "#ebdefc"
color14 = "#c6efe9"
color15 = "#ffeca0"
